// ///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
// class Assets {
//   Assets._();

//   static const String iconsRightArrow = 'assets/icons/right_arrow.svg';
//   static const String iconsShare = 'assets/icons/share.svg';
//   static const String iconsWhatsapp = 'assets/icons/whatsapp.svg';
//   static const String iconsBellDot = 'assets/icons/bell_dot.svg';
//   static const String iconsCalendar = 'assets/icons/calendar.svg';
//   static const String iconsCheckboxChecked = 'assets/icons/checkbox_checked.svg';
//   static const String iconsCheckboxUnchecked = 'assets/icons/checkbox_unchecked.svg';
//   static const String iconsChevronDown = 'assets/icons/chevron_down.svg';
//   static const String iconsPin = 'assets/icons/pin.svg';
//   static const String iconsSearch = 'assets/icons/search.svg';
//   static const String imagesOb1 = 'assets/images/ob1.svg';
//   static const String imagesOb2 = 'assets/images/ob2.svg';
//   static const String imagesOb3 = 'assets/images/ob3.svg';
//   static const String imagesSplashBg = 'assets/images/splash_bg.png';
//   static const String imagesLineThrough = 'assets/images/line_through.png';
//   static const String logoPocLogo = 'assets/logo/poc_logo.png';
// }
